name: deploy cloud proxy

on: [push]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: run docker-compose
        uses: blag/action-docker-compose@latest
        with:
          # https://docs.docker.com/compose/reference/overview/
          cli-args: "up --build -d"
