name: deploy cloud proxy

on: [push]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker/docker-compose.yml"
